apiVersion: v1
kind: Service
metadata:
  name: postgresql-db-service
spec:
  selector:
    app: postgresql-db
  ports:
  - name: post-ser
    protocol: TCP
    port: 5432
    targetPort: 5432
  clusterIP: None