apiVersion: v1                                                                      false                  4d15h
kind: PersistentVolumeClaim
metadata:
  name: postgresql-db-disk
spec:
  storageClassName: local-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi