name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    # Set up SSH to access the remote server
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan 34.135.120.96 >> ~/.ssh/known_hosts

    # Build the Docker image
    - name: Build the Docker image
      run: |
        docker build -t ganeshd2532/prod_data:1 .

    # List the images (for debugging purposes)
    - name: List the images
      run: |
        docker images
        pwd

    # Set up QEMU (if building multi-platform images)
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    # Set up Docker Buildx (for building multi-platform images)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Log in to Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Push the built image to Docker Hub
    - name: Build and push
      run: docker push ganeshd2532/prod_data:1
